name: thz-daq
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - gettext=0.21.1=h5728263_0
  - glib=2.78.3=h12be248_0
  - glib-tools=2.78.3=h12be248_0
  - gst-plugins-base=1.22.9=h001b923_0
  - gstreamer=1.22.9=hb4038d2_0
  - icu=73.2=h63175ca_0
  - krb5=1.21.2=heb0366b_0
  - libclang=15.0.7=default_hde6756a_4
  - libclang13=15.0.7=default_h85b4d89_4
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.78.3=h16e383f_0
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.42=h19919ed_0
  - libsqlite=3.44.2=hcfcfb64_0
  - libvorbis=1.3.7=h0e60522_0
  - libxml2=2.12.5=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - openssl=3.2.1=hcfcfb64_0
  - packaging=23.2=pyhd8ed1ab_0
  - pcre2=10.42=h17e33f8_0
  - pip=24.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pyqt=5.15.9=py310h1fd54f2_5
  - pyqt5-sip=12.12.2=py310h00ffb61_5
  - pyqtads=4.2.0=py310he49db7d_0
  - python=3.10.13=h4de0772_1_cpython
  - python_abi=3.10=4_cp310
  - qt-main=5.15.8=h9e85ed6_18
  - qt5-advanced-docking-system=4.2.1=hf2d14a9_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sip=6.7.12=py310h00ffb61_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zstd=1.5.5=h12be248_0
  - pip:
      - altgraph==0.17.4
      - alvar==0.1.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - idna==3.6
      - numpy==1.26.3
      - pefile==2023.2.7
      - pillow==10.2.0
      - pyinstaller==6.3.0
      - pyinstaller-hooks-contrib==2024.0
      - pymodbus==3.6.3
      - pyqtgraph==0.13.3
      - pyserial==3.5
      - pywin32-ctypes==0.2.2
      - requests==2.31.0
      - urllib3==2.2.0
